FROM node:22 as builder
WORKDIR /app
RUN apt-get update && apt-get install libcairo2-dev libjpeg-dev libgif-dev libpango1.0-dev -y
COPY package.json package-lock.json ./
RUN npm install --omit=dev
COPY . .

#Runtime
FROM gcr.io/distroless/nodejs20-debian12
WORKDIR /app
COPY --from=builder /app .
CMD node server.js