FROM node:22 as builder
WORKDIR /app
RUN apt-get update && apt-get install libcairo2-dev libjpeg-dev libgif-dev libpango1.0-dev -y
COPY package.json package-lock.json ./
RUN npm install
COPY . .

#Runtime
FROM node:22-slim
WORKDIR /app
COPY --from=builder /app .
RUN npm install --only=production

CMD node server.js

