FROM node:22-slim
WORKDIR /app
RUN apt-get update && apt-get install libcairo2-dev libjpeg-dev libgif-dev libpango1.0-dev -y
COPY package.json package-lock.json ./
RUN npm install
COPY . .
CMD node server.js
